### ISSUE TITLE
Compiling high_dim_filter.so on Raspbian

### ISSUE THREAD

**Issue by kubmin** [sadeepj/crfasrnn_keras#18]
Hi all,

After successfully compiling and running the demo, I am trying to compile the custom C++ code on a Raspberry running Raspbian 9 (Stretch). I'm running the regular ./compile.sh script, however I'm getting the following error:

`$ ./compile.sh`
`In file included from /home/pi/.local/lib/python3.5/site-packages/tensorflow/include/tensorflow/core/framework/attr_value_util.h:23:0,
                 from /home/pi/.local/lib/python3.5/site-packages/tensorflow/include/tensorflow/core/framework/node_def_util.h:23,
                 from /home/pi/.local/lib/python3.5/site-packages/tensorflow/include/tensorflow/core/framework/shape_inference.h:21,
                 from high_dim_filter.cc:26:
/home/pi/.local/lib/python3.5/site-packages/tensorflow/include/tensorflow/core/framework/tensor.h: In member function ‘void tensorflow::Tensor::FillDimsAndValidateCompatibleShape(Eigen::array<int, NDIMS>*, tensorflow::gtl::ArraySlice<long long int>) const [with unsigned int NDIMS = 1u]’:
/home/pi/.local/lib/python3.5/site-packages/tensorflow/include/tensorflow/core/framework/tensor.h:574:6: note: parameter passing for argument of type ‘tensorflow::gtl::ArraySlice<long long int>’ will change in GCC 7.1
 void Tensor::FillDimsAndValidateCompatibleShape(
      ^~~~~~
modified_permutohedral.cc: In member function ‘void ModifiedPermutohedral::init(const float*, int, int)’:
modified_permutohedral.cc:362:22: error: ‘feature’ was not declared in this scope
   const float * f = (feature + k * num_dimensions);`

I tried searching for solutions at the Tensorflow page you provided, tried out some their python code, but the same error popped up. Do you got any ideas on how to successfully compile the code on Raspbian? I would love to hear from you!

Best,

Boris.

**Comment by sadeepj** [comment]
@kubmin Looking at the source code https://github.com/sadeepj/crfasrnn_keras/blob/master/cpp/modified_permutohedral.cc, it looks like Raspbian is trying to compile a part of that file that is not activated on other compilers due to the #ifdef directives. This particular compilation error is due to a typo ('feature' instead 'features'). As the first step, I would correct that typo and try again. Unfortunately, I'm unable to test it myself since I don't have access to Raspbian.

As you can see from the header comment of modified_permutohedral.cc, I'm not the original author of that code. I have little understanding of how exactly it behaves on Raspbian.
